#PyThon CicleCI 2.0 configuataion file
version: 2
jobs:
  build:
    docker :
      - image: circleci/python:3.9
    working_directory: ~/repo

    steps:
      #Step 1 : Obtaining repo from github
      -checkout
      #Step2: Creating the virtual enviroment and installing dependencies
      - run:
        name: Install dependencies
        comand: |
          python3 -m venv venv
          .venv/bin/activate
          pip install -r  requirements.txt

      #Step 3  run the linter and tests
      - run:
        name: run test
        command: |
            .venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=Calculator